# Generated by Django 5.0.6 on 2024-07-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_id', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('image', models.URLField()),
                ('summary', models.TextField()),
                ('source_url', models.URLField()),
            ],
        ),
    ]
