# Generated by Django 5.0.6 on 2024-07-04 05:37

import jsonfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='image',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='summary',
        ),
        migrations.AddField(
            model_name='recipe',
            name='data',
            field=jsonfield.fields.JSONField(default='Default'),
            preserve_default=False,
        ),
    ]
