# Generated by Django 5.0.6 on 2024-07-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0002_remove_recipe_image_remove_recipe_source_url_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='data',
            new_name='ingredients',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='source_url',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='recipe',
            name='summary',
            field=models.TextField(default=''),
        ),
    ]
