# Generated by Django 5.0.6 on 2024-07-04 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0003_rename_data_recipe_ingredients_recipe_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='dish_types',
            field=models.TextField(default=[]),
        ),
    ]
