# Generated by Django 5.0.6 on 2024-07-04 18:42

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0005_recipe_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='dish_types',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=jsonfield.fields.JSONField(default=''),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
