# Generated by Django 5.0.6 on 2024-07-08 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0008_alter_recipe_instructions_pantryitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='in_stock',
            field=models.BooleanField(default=False),
        ),
    ]
