# Generated by Django 5.0.6 on 2024-07-13 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0010_alter_pantryitem_in_stock_alter_pantryitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='expiration_date',
            field=models.DateField(blank=True, default='2024-07-12'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
