# Generated by Django 5.0.6 on 2024-07-13 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0011_alter_pantryitem_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pantryitem',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pantryitem',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
