# Generated by Django 5.0.6 on 2024-07-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0013_alter_pantryitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='pantryitem',
            name='units',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
