# Generated by Django 5.0.6 on 2024-07-26 21:48

import jsonfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pantry', '0015_favoriterecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient_id', models.IntegerField()),
                ('name', models.CharField(default='', max_length=255)),
                ('substitutes', jsonfield.fields.JSONField(default='')),
            ],
        ),
        migrations.AddField(
            model_name='recipe',
            name='cuisines',
            field=models.TextField(default=''),
        ),
    ]
